/*
 * This source file was generated by the Gradle 'init' task
 */
package week.kamen.raideh;
import week.kamen.raideh.CoreMedal.MedalName;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

public static void main(String[] args) {
    OOODriver driver = new OOODriver();
    ComboCatalogue catalogue = new ComboCatalogue();
    TransformationEngine engine = new TransformationEngine(catalogue);
    OScanner scanner = new OScanner(engine);
    System.out.println(scanner.scan(driver));

    // TODO : Let users select actions from a menu instead of a one-time demo flow & Optoion to see history
      
    driver.insertMedal(new CoreMedal(MedalName.TAKA));
    driver.insertMedal(new CoreMedal(MedalName.TORA));
    driver.insertMedal(new CoreMedal(MedalName.BATTA));

    }
}
