/*
 * This source file was generated by the Gradle 'init' task
 */
package week.kamen.raideh;
import week.kamen.raideh.CoreMedal.MedalName;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
      OOODriver driver = new OOODriver();
      driver.insertMedal(new CoreMedal(MedalName.TAKA));
      driver.insertMedal(new CoreMedal(MedalName.TORA));
      driver.insertMedal(new CoreMedal(MedalName.BATTA));
      ComboCatalogue catalogue = new ComboCatalogue();
      TransformationEngine engine = new TransformationEngine(catalogue);
      OScanner scanner = new OScanner(engine);
      System.out.println(scanner.scan(driver));

    }
}
